const researches = [
  {
    id: 1,
    endDate: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    rating: 5,
  },
  {
    id: 2,
    endDate: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    rating: 3,
  },
  {
    id: 3,
    endDate: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    rating: 4.5,
  },
  {
    id: 4,
    endDate: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    rating: 2.5,
  },
  {
    id: 5,
    endDate: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    rating: 1,
  },
  {
    id: 6,
    endDate: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    rating: 2,
  },
  {
    id: 7,
    endDate: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    rating: 1.5,
  },
  {
    id: 8,
    endDate: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    rating: 3,
  },
  {
    id: 9,
    endDate: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    rating: 4.5,
  },
  {
    id: 10,
    endDate: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    rating: 1,
  },
]

export default researches
