const researches = [
  {
    id: 1,
    nextContact: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    email: 'mateus@sicoob.org.br',
    phone: '00 11111-2222',
    daysLeft: 14,
  },
  {
    id: 2,
    nextContact: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    email: 'thiago@sicoob.org.br',
    phone: '11 22222-3333',
    daysLeft: 20,
  },
  {
    id: 3,
    nextContact: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    email: 'samuel@sicoob.org.br',
    phone: '22 33333-4444',
    daysLeft: 23,
  },
  {
    id: 4,
    nextContact: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    email: 'mateus@sicoob.org.br',
    phone: '00 11111-2222',
    daysLeft: 14,
  },
  {
    id: 5,
    nextContact: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    email: 'thiago@sicoob.org.br',
    phone: '11 22222-3333',
    daysLeft: 20,
  },
  {
    id: 6,
    nextContact: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    email: 'samuel@sicoob.org.br',
    phone: '22 33333-4444',
    daysLeft: 23,
  },
  {
    id: 7,
    nextContact: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    email: 'mateus@sicoob.org.br',
    phone: '00 11111-2222',
    daysLeft: 14,
  },
  {
    id: 8,
    nextContact: '17/04/2020',
    service: 'Projeto Segurança',
    cooperative: 'Sicoob Lagoacred Gerais',
    responsible: 'Thiago Munich',
    email: 'thiago@sicoob.org.br',
    phone: '11 22222-3333',
    daysLeft: 20,
  },
  {
    id: 9,
    nextContact: '20/04/2020',
    service: 'Kace',
    cooperative: 'Sicoob Cosmipa',
    responsible: 'Samuel Lopes',
    email: 'samuel@sicoob.org.br',
    phone: '22 33333-4444',
    daysLeft: 23,
  },
  {
    id: 10,
    nextContact: '11/04/2020',
    service: 'ICL',
    cooperative: 'Sicoob Aracoop',
    responsible: 'Mateus Lopes',
    email: 'mateus@sicoob.org.br',
    phone: '00 11111-2222',
    daysLeft: 14,
  },
]

export default researches
